# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddev < Formula
  desc "DDEV"
  homepage "https://github.com/drud/ddev"
  version "1.19.4"
  license "Apache 2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drud/ddev/releases/download/v1.19.4/ddev_macos-amd64.v1.19.4.tar.gz"
      sha256 "57d812316b61d096f69396dc65621a0c9d980f7646a793d24f1b0c52e2cd0857"

      def install
        if build.head?
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
        else
            bin.install "ddev"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drud/ddev/releases/download/v1.19.4/ddev_macos-arm64.v1.19.4.tar.gz"
      sha256 "cf11ad950d145e5fde966ed13ca1ef717703a9ed8b7298674673d35f5c46bb64"

      def install
        if build.head?
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
        else
            bin.install "ddev"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drud/ddev/releases/download/v1.19.4/ddev_linux-arm64.v1.19.4.tar.gz"
      sha256 "24ebdac1956c8bf3ccc02fd9382a175a33dc221ead0c8613919cb4ce13860147"

      def install
        if build.head?
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
        else
            bin.install "ddev"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drud/ddev/releases/download/v1.19.4/ddev_linux-amd64.v1.19.4.tar.gz"
      sha256 "38b9c703bb5fe1e441de41d32e112d0e27c78c28d9af623903911a0a54d6d0e1"

      def install
        if build.head?
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
        else
            bin.install "ddev"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev"
        end
      end
    end
  end

  head "https://github.com/drud/ddev.git", branch: "master"
  depends_on "go" => :build
  depends_on "make" => :build

  depends_on "mkcert"

  test do
    system "#{bin}/ddev --version"
  end
end
